name: CBO-CapTax
channels:
  - defaults
dependencies:
  - python==3.8.5
  - colorama==0.4.4
  - ipykernel==5.3.4
  - ipython==7.19.0
  - numpy==1.19.2
  - pandas==1.1.3
  - pyyaml==5.4.1
  - spyder==4.2.5
  - xlsxwriter==1.3.8
